repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.2
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args:
          - --skip=tests/test_emails/*,custom_components/mail_and_packages/translations/*
          - --ignore-words-list=hass,numer,ist,paket,pakets,adresse,deine,ons,fo,te,nome,generare,impossibile
        additional_dependencies:
          - tomli
