name: Request a feature for Mail and Packages
labels: ["feature"]
title: "[Feature Request]: "
description: Request a feature for Mail and Packages.
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: The feature
      description: >-
        Describe the feature you'd like added.
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.