################################################################
## Mail and Packages
## Yaml coding based on happyleavesaoc https://github.com/happyleavesaoc/my-home-automation/blob/master/homeassistant/packages/deliveries.yaml
## Pyhton code based on @skalavala work at https://blog.kalavala.net/usps/homeassistant/mqtt/2018/01/12/usps.html
## Mail Card based on Bram_Kragten work at https://community.home-assistant.io/t/custom-ui-weather-state-card-with-a-question/23008
################################################################

# LoveLace Crad Configuration
# 
#       - deliver_today: sensor.mail_deliveries_today
#         fedex: sensor.mail_fedex_packages
#         in_transit: sensor.mail_packages_in_transit
#         last_update: sensor.mail_updated
#         mail: sensor.mail_usps_mail
#         summary: sensor.mail_deliveries_message
#         type: 'custom:mail-and-packages'
#         ups: sensor.mail_ups_packages
#         usps: sensor.mail_usps_packages

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'Mail and Packages'

      expose: &expose
        <<: *customize
        haaska_hidden: true
        homebridge_hidden: true

    ################################################
    ## Icons
    ################################################
  
    sensor.mail_updated:
      <<: *customize
      friendly_name: Mail Updated
      
    sensor.mail_usps_mail:
      <<: *customize
      friendly_name: Mail
      icon: mdi:email-outline
    sensor.mail_usps_delivering:
      <<: *customize
      friendly_name: USPS Delivering
    sensor.mail_usps_delivered:
      <<: *customize
      friendly_name: USPS Delivered
    sensor.mail_usps_packages:
      <<: *customize
      friendly_name: USPS Packages
      
    sensor.mail_ups_delivering:
      <<: *customize
      friendly_name: UPS Delivering
    sensor.mail_ups_delivered:
      <<: *customize
      friendly_name: UPS Delivered
    sensor.mail_ups_packages:
      <<: *customize
      friendly_name: UPS Packages
      
    sensor.mail_fedex_delivering:
      <<: *customize
      friendly_name: FedEx Delivering
    sensor.mail_fedex_delivered:
      <<: *customize
      friendly_name: FedEx Delivered
    sensor.mail_fedex_packages:
      <<: *customize
      friendly_name: FedEx Packages
   
    input_text.mail_delivery_summary:
      <<: *customize
    sensor.mail_deliveries_today:
      <<: *customize
      icon: mdi:package-variant
    sensor.mail_packages_in_transit:
      <<: *customize
      icon: mdi:truck-delivery
    sensor.mail_deliveries_message:
      <<: *customize
      
    automation.notif_mail_delieveries:
      <<: *customize

################################################
## Mail and Packages Platform
################################################   
# NOT IMPLEMENTED HARD CODE THIS IN THE SENSOR.PY
#mail_and_packages:
#  host: !secret mail_host
#  port: !secret mail_port
#  username: !secret mail_username
#  password: !secret mail_password
#  folder: 'Inbox'
#  image_output_path: !secret mail_image_output_path

################################################
## Sensors
################################################    

sensor:
  - platform: mail_and_packages
    host: !secret mail_host
#.   port: !secret mail_port Using Default Port
    username: !secret mail_username
    password: !secret mail_password
#    folder: 'Inbox' Using Deafult Folder
#     image_path: !secret mail_image_output_path Using Default Path   
          
  - platform: template
    sensors:
      mail_usps_packages:
        friendly_name: "USPS Packages"
        entity_id: 
          - sensor.mail_usps_delivering
          - sensor.mail_usps_delivered
        unit_of_measurement: 'Packages'
        value_template: "{{ states('sensor.mail_usps_delivering')|int - states('sensor.mail_usps_delivered')|int + states('sensor.mail_usps_delivered')|int }}"
  
  - platform: template
    sensors:
      mail_fedex_packages:
        friendly_name: "FedEx Packages"
        entity_id: 
          - sensor.mail_fedex_delivering
          - sensor.mail_fedex_delivered
        unit_of_measurement: 'Packages'
        value_template: "{{ states('sensor.mail_fedex_delivering')|int - states('sensor.mail_fedex_delivered')|int + states('sensor.mail_fedex_delivered')|int }}"
        
  - platform: template
    sensors:
      mail_ups_packages:
        friendly_name: "UPS Packages"
        entity_id: 
          - sensor.mail_ups_delivering
          - sensor.mail_ups_delivered
        unit_of_measurement: 'Packages'
        value_template: "{{ states('sensor.mail_ups_delivering')|int - states('sensor.mail_ups_delivered')|int + states('sensor.mail_ups_delivered')|int }}"

  - platform: template
    sensors:
      mail_packages_in_transit:
        friendly_name: "Packages in Transit"
        entity_id: 
          - sensor.mail_usps_delivering
          - sensor.mail_usps_delivered
          - sensor.mail_fedex_delivering
          - sensor.mail_fedex_delivered
          - sensor.mail_ups_delivering
          - sensor.mail_ups_delivered
          - sensor.mail_usps_mail
        unit_of_measurement: 'Packages'
        value_template: >
          {% macro in_transit(sensor) %}
            {% if states(sensor) != "unknown" %}
              {{states(sensor)|int - delivered(sensor)|int}}
            {% else %}
               none
            {% endif %}
          {% endmacro %}
          {% macro delivered(sensor) %}
            {% if states(sensor) != "unknown" and state_attr(sensor, "delivered") != "undefined" %}
                {{ state_attr(sensor, "delivered")}}
              {% else %}
                 none
              {% endif %}
          {% endmacro %}
          {{in_transit("sensor.mail_ups")|int + ( in_transit("sensor.mail_usps_delivering")|int - in_transit("sensor.mail_usps_delivered")|int ) + ( in_transit("sensor.mail_fedex_delivering")|int - in_transit("sensor.mail_fedex_delivered")|int )}}
      mail_deliveries_today:
        friendly_name: "Today's Deliveries"
        entity_id: 
          - sensor.mail_usps_delivering
          - sensor.mail_usps_delivered
          - sensor.mail_fedex_delivered
          - sensor.mail_ups_delivering
          - sensor.mail_ups_delivered
          - sensor.mail_usps_mail
        unit_of_measurement: 'Packages'
        value_template: >
          {% macro delivered(sensor) %}
            {% if states(sensor) != "unknown" and state_attr(sensor, "delivered") != "undefined" %}
                {{ state_attr(sensor, "delivered")}}
              {% else %}
                 none
              {% endif %}
          {% endmacro %}
          {% macro out_delivering(sensor) %}
            {% if states(sensor) != "unknown" and state_attr(sensor, "out_for_delivery") != "undefined" %}
                {{ state_attr(sensor, "out_for_delivery")}}
              {% else %}
                 none
              {% endif %}
          {% endmacro %}
          {#{delivered("sensor.mail_usps_delivered")|int + delivered("sensor.mail_fedex_delivered")|int + delivered("sensor.mail_ups")|int + out_delivering("sensor.mail_usps_delivered")|int + out_delivering("sensor.mail_fedex_delivered")|int + out_delivering("sensor.mail_ups")|int + states("sensor.mail_usps_delivered")|int}#}
          {# Becuase the official USPS and FedEx components are broken we replace the above output with what is below#}
          {{delivered("sensor.mail_ups")|int + out_delivering("sensor.mail_ups")|int +  states("sensor.mail_usps_delivered")|int + states("sensor.mail_fedex_delivered")|int}}

      mail_deliveries_message:
        friendly_name: "Deliveries Summary"
        entity_id: 
          - sensor.mail_usps_delivering
          - sensor.mail_usps_delivered
          - sensor.mail_fedex_delivering
          - sensor.mail_fedex_delivered
          - sensor.mail_ups_delivering
          - sensor.mail_ups_delivered
          - sensor.mail_usps_mail
          - sensor.mail_deliveries_today
        value_template: > 
          {# Deliveries Sentence #}
            {% macro deliveries_sentence() -%}
                 {%- if states("sensor.mail_usps_mail")|int == 0 -%}
                    No
                  {%- else -%}
                    {{states("sensor.mail_usps_mail")|int}}
                  {%- endif -%}
                {{' '}} 
                  {%- if states("sensor.mail_usps_mail")|int <= 1 -%}
                    mail
                  {%- else -%}
                    pieces of mail
                  {%- endif -%}
                {{' '}}will be delivered.{{' '}} 
                 {%- if states("sensor.mail_packages_in_transit")|int == 0 -%}
                    No
                  {%- else -%}
                    {{states("sensor.mail_packages_in_transit")|int}}
                  {%- endif -%}
                {{' '}} 
                  {%- if states("sensor.mail_packages_in_transit")|int == 1 -%}
                    package is
                  {%- else -%}
                    packages are
                  {%- endif -%}
                {{' '}}in transit.{{' '}}
                {%- if states("sensor.mail_deliveries_today")|int == 0 -%}
                    No
                  {%- else -%}
                    {{states("sensor.mail_deliveries_today")|int}}
                  {%- endif -%}
                {{' '}}
                  {%- if states("sensor.mail_deliveries_today")|int == 1 -%}
                    package
                  {%- else -%}
                    packages
                  {%- endif -%}
                {{' '}}should be delivered today.
            {%- endmacro %}
          {{deliveries_sentence()}}


################################################
## Automations
################################################  

automation:
- alias: 'Mail Notif: Mail Delieveries'
  initial_state: true
  trigger:
  #Trigger if mail or packages get updated
    - platform: state
      entity_id: sensor.mail_deliveries_today
    - platform: state
      entity_id: sensor.mail_usps_mail
  #send only if mail or packages are more than 0
  condition:
    - condition: or
      conditions:
        - condition: template
          value_template: "{{ states('sensor.mail_deliveries_today') | int > 0 }}"
        - condition: template
          value_template: "{{ states('sensor.mail_usps_mail') | int > 0 }}"
  action:
    - delay: '00:00:20'
    - service_template: >
        notify.{{ states('input_select.notify_select') }}
      data_template:
        title: "Mail and Packages"
        message: "{{ states('sensor.mail_deliveries_message')}}"
        data:
          attachment:
            url: https://treehouse.munkyhome.com/local/mail_and_packages/mail_today.gif
            hide-thumbnail: false
          push:
            thread-id: "homeassistant-mail"
