name: Release Drafter

on:
  push:
    branches:
      - master
      - 0.2.0
      - 0.3.0

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
